export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const LOAD_ERROR = 'LOAD_ERROR';
export const UNLOAD_ERROR = 'UNLOAD_ERROR';
export const UNLOAD_STORE = 'UNLOAD_STORE';
export const CHANGE_LANGUAGE_HUN = 'CHANGE_LANGUAGE_HUN';
export const CHANGE_LANGUAGE_ENG = 'CHANGE_LANGUAGE_ENG';
export const LOAD_EVENTS_DATA = 'LOAD_EVENTS_DATA';